config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  devise_for :users,
               :path => '', 
               :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
               :controllers => {:registrations => 'registrations' } 

  resources :users, only: [:show]
  resources :engines do
    resources :saves, only: [:create]
  end
  resources :photos
  

end

app/models/engine.rb
class Engine < ActiveRecord::Base
    
    belongs_to:user
    has_many :photos
    has_many :saves
    
    validates :engine_name, presence: true, length: {maximum: 25}
    validates :engine_description, presence: false, length: {maximum: 600}
    validates :engine_identity, presence: true, length: {maximum: 75}
    validates :engine_define, presence: true
	
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :engine

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }      
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/ 

end

app/models/save.rb
class Save < ActiveRecord::Base
  belongs_to :user
  belongs_to :engine
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :fullname, presence: true, length: {maximum: 65}
  
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/default_image.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_many :engines
  has_many :saves
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
      devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :avatar, :description, :email, :password, :password_confirmation])
  end
end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
    
    before_action :set_engine, only: [:show, :edit, :update]
    before_action :authenticate_user!, except: [:show]
    before_action :require_same_user, only: [:edit, :update]

    def index
        @engines = current_user.engines
    end
    
    def new
        @engine = current_user.engines.build
    end
    
    def create
        @engine = current_user.engines.build(engine_params)
        if @engine.save
            if params[:images]
                params[:images].each do |i|
                    @engine.photos.create(image: i)
                end
            end
            @photos = @engine.photos
            redirect_to edit_engine_path(@engine), notice:"Votre moteur à bien étais enregistrer."
        else
            render :new
        end
    end
    
    def show
        @photos = @engine.photos
    end
    
    def edit
        @photos = @engine.photos
    end
    
    def update
        if @engine.update(engine_params)
            if params[:images]
                params[:images].each do |i|
                    @engine.photos.create(image: i)
                end
            end
            @photos = @engine.photos
            redirect_to edit_engine_path(@engine), notice:"Modification enregistrée..."
        else
            render :edit
        end
    end
    
    private
        
        def require_same_user
            if current_user.id != @engine.user_id
                flash[:danger] = "Vous n'avez pas le droit de modifier cette page"
                redirect_to root_path
            end
        end
        
        def set_engine
            @engine = Engine.find(params[:id])
        end
          
        def engine_params
            params.require(:engine).permit(:engine_name, :engine_description, :engine_identity, :engine_define)
        end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    def destroy
        @photo = Photo.find(params[:id])
        engine = @photo.engine
        @photo.destroy
        @photos = Photo.where(engine_id: engine.id)
        respond_to :js
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
 protected
 
 def update_resource(resource, params)
     resource.update_without_password(params)
 end
 
end

app/controllers/saves_controller.rb
class SavesController < ApplicationController

    before_action :authenticate_user!

    def create
        @save = current_user.saves.create(save_params)       
        redirect_to @save.engine, notice: "Votre page a bien été sauvegarder."
    end
 
  
    private
        def save_params         
            params.require(:save).permit(:start_date, :engine_id)     
        end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def avatar_url(user)
        user.avatar.url
    end
end

app/views/engines/_form.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        Nouveau formulaire
    </div>
    <div class="panel-body">
        <div class="container">
            
            <%= form_for @engine, html: {multipart: true} do |f| %>
                <%= render 'layouts/errors' %> 
                <div class="row">
                        <div class="form-group">
                            <label>Nouveau formulaire</label>
                            <%= f.text_field :engine_name, placeholder: "Nouveau formulaire", class: "form-control" %>
                        </div>
                    </div>
                        
                <div class="row">
                        <div class="form-group">
                            <label>Description</label>
                            <%= f.text_area :engine_description, rows:3, placeholder: "Nouveau formulaire",
                            class: "form-control" %>
                        </div>
                    </div>

                <div class="row">
                        <div class="form-group">
                            <label>Nouveau formulaire</label>
                            <%= f.text_field :engine_identity, placeholder: "Nouveau formulaire", class: "form-control" %>
                        </div>
                    </div>
                    
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <span class="btn btn-default btn-file">
                            <i class = "fa fa-cloud-upload fa-lg"></i> Téléchargez une photo de couverture
                            <%= file_field_tag "images[]", type: :file, multiple: true %>
                            </span>
                        </div>
                    </div>
                 </div>
                
                <div id="photos"><%= render 'photos/list' %></div>
                
                <div class="actions">
                    <%= f.submit "Publier", class: "btn btn-primary"%>
                </div>
            <% end %>
            
        </div>
    </div>
</div>

app/views/engines/edit.html.erb
<%= render 'form' %>

app/views/engines/index.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
           <li class="sidebar-item"><%= link_to "Mes publications", engines_path, class: "sidebar-link active" %></li>
        </ul>
    </div>
       <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">Mes publications</div>
                    <div class="panel-body">
                        <% @engines.each do |engine| %>
                            <div class="row">
                                <div class="col-md-2">
                                    <%= image_tag engine.photos[0].image.url(:thumb) if engine.photos.length > 0 %> 
                                </div>                              
                                <div class="col-md-7">
                                    <h4><%= engine.engine_name %></h4>
                                </div>                              
                                <div class="col-md-3 right">
                                    <%= link_to "Mettre à jour", edit_engine_path(engine), class: "btn btn-primary" %>
                                </div>
                            </div>
                        <hr>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>

app/views/engines/new.html.erb
<%= render 'form' %>

app/views/engines/show.html.erb
<div class="panel panel-default">
    <div class="panel-body">
        
        <!-- Photo principale de l'annonce -->
        <div class="row">
            <div class="col-md-12">
                <%= image_tag @photos[0].image.url(), class:"img-responsive" if @photos.length >0 %>
            </div>
        </div>
        
        <br>
        
        <!-- Informations principales -->
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-3 text-center">
                        <%= image_tag avatar_url(@engine.user), class:"img-circle avatar-large" %>
                        <br>
                        <br>
                        <%= @engine.user.fullname %>
                    </div>
                    <div class="col-md-9">
                        <h4><%= @engine.engine_identity %></h4>
                        <%= @engine.engine_name %>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <!-- Formulaire de réservation -->
                <%= render 'saves/form' %>
            </div>
        </div>
        
        <!-- Description -->
        <div class="row">
            <div class="col-md-12">
                <h2> </h2>
                <p><%= @engine.engine_define %></p>
            </div>
        </div>
        
        </div>
    </div>
</div>

app/views/layouts/_devise_errors.html.erb
<% unless resource.errors.empty? %>
    <script type="text/javascript">
        <% resource.errors.full_messages.each do |msg| %>
            toastr.error('<%= msg %>')
        <% end %>
    </script>
<% end %>

app/views/layouts/_errors.html.erb
<% unless @engine.errors.empty? %>
    <script type="text/javascript">
        <% @engine.errors.full_messages.each do |msg| %>
            toastr.error('<%= msg %>')
        <% end %>
    </script>
<% end %>

app/views/layouts/_message.html.erb
<% unless flash.empty? %>
 
       <script type="text/javascript">
 
       <% flash.each do |f| %>
 
        <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
 
         toastr['<%= type %>']('<%= f[1] %>')
 
       <% end %>
 
       </script>
 
 <% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" 
data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Deus', root_path, { :class=>"navbar-brand" } %>
        </div>
        <div id="navbar" class="navbar-collapse collapse right">
          <ul class="nav navbar-nav navbar-right">
            
            <li>
              <%= link_to new_engine_path do %>
                <i class="fa fa-hashtag"></i> Nouveau
              <% end %>
            </li>
            
            <% if (!user_signed_in?) %>
                <li><%= link_to 'Inscription', new_user_registration_path %></li>
                <li><%= link_to 'Connexion', new_user_session_path %></li>
                
            <% else %>
            
                <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-haspopup="true" aria-expanded="false">
                <%= image_tag avatar_url(current_user), class:"img-circle avatar-small" %> <%= current_user.fullname %>
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Mes voyages", root_path %></li>
                <li><%= link_to 'Modifier mon profil', edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Déconnexion', destroy_user_session_path, 
method: :delete %></li>
              </ul>
            </li>
            <% end %>
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Deus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <%= favicon_link_tag 'favicon.ico' %>
  
</head>
<body>

<%= render 'layouts/navigation' %>
<%= render 'layouts/message' %>

<div class="container"><%= yield %></div>
<meta name="viewport" content="width=device-width, initial-scale=1">
</body>
</html>

app/views/photos/_list.html.erb
<% if @photos %>
    <div class="row">
      <% @photos.each do |photo|  %>
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading preview">
              <%= image_tag photo.image.url() %>
            </div>
            <div class="panel-body">
              <span class="pull-right">
                <%= link_to photo, remote: true, method: :delete, data: {confirm: "Certain de vouloir supprimer cette photo?"} do %>  
                  <i class="fa fa-times fa-lg"></i>
                <% end %>
              </span>
            </div>
          </div>
        </div>
      <% end %>
    </div>
<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos/list' %>")

app/views/saves/_form.html.erb
<%= form_for([@engine, @engine.saves.new]) do |f| %>
    <%= f.text_field :start_date %>
    <%= f.hidden_field :engine_id, value: @engine.id %>
	<br/>
	<%= f.submit "Sauvegarde de la publication", class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-3">
        <%= image_tag avatar_url(@user), class:"avatar-full" %>
        <div class="panel panel-default">
            <div class="panel-heading">Vérification</div>
                <div class="panel-body">
                    Email: <%= @user.email %>
                </div>
        </div>
    </div>
    <div class="col-md-9">
        <h2><%= @user.fullname %></h2>
        <div class="description row-space-3">
            <%= @user.description %>
        </div>
    </div>
</div>